// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"contacts/controllers"
	"contacts/jobs"
	"contacts/repositories"
	"contacts/routers"
	"contacts/services"
)

// Injectors from wire.go:

func initializeDependencies() Server {
	db := repositories.ProvideGormFromEnv()
	userRepository := repositories.ProvideUserRepository(db)
	userService := services.ProvideUserService(userRepository)
	userController := controllers.ProvideUserController(userService)
	userContactRepository := repositories.ProvideUserContactRepository(db)
	userContactModificationRepository := repositories.ProvideUserContactModificationRepository(db)
	userContactService := services.ProvideUserContactService(userContactRepository, userContactModificationRepository)
	userContactController := controllers.ProvideUserContactController(userContactService)
	router := routers.ProvideRouter(userController, userContactController)
	migrationJob := jobs.ProvideMigrationJob()
	v := jobs.ProvideOnStartUpJob(migrationJob)
	mainServer := provideServer(router, v)
	return mainServer
}
